// GENERATED by scripts/sync-plugin-core.mjs from plugins/core — edit there, then re-run the sync.
// transcript.js — client transcript readers. Two jobs: the assistant's text
// (to judge which retrieved memories a session actually USED) and a tool-use
// count (to decide whether a session was substantive enough for the stop
// nudge). Unknown shapes are reported as !recognized so callers can refuse
// to judge rather than guess.
import { readFileSync } from "node:fs";

export function readTranscript(p) {
  try { return readFileSync(p, "utf8"); } catch { return null; }
}
function lines(text) {
  const out = [];
  for (const line of String(text ?? "").split("\n")) {
    if (!line.trim()) continue;
    try { const o = JSON.parse(line); if (o && typeof o === "object") out.push(o); } catch { /* skip */ }
  }
  return out;
}
function textOf(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content.filter((b) => b && typeof b === "object" && b.type === "text" && typeof b.text === "string").map((b) => b.text).join("\n");
}
const TOOL_BLOCK = new Set(["tool_use", "tool_call", "toolCall"]);
function toolBlocks(content) {
  return Array.isArray(content) ? content.filter((b) => b && typeof b === "object" && TOOL_BLOCK.has(b.type)).length : 0;
}

export function parseClaude(text) {
  const parts = []; let toolUses = 0; let recognized = false;
  for (const o of lines(text)) {
    if (o.type !== "assistant") continue;
    recognized = true;
    const c = o.message?.content;
    const t = textOf(c); if (t) parts.push(t);
    toolUses += toolBlocks(c);
  }
  return { assistantText: parts.join("\n"), toolUses, recognized };
}

/** SYNTHETIC shape until spec D4 pins the real Cursor transcript JSONL. */
export function parseCursor(text) {
  const parts = []; let toolUses = 0; let recognized = false;
  for (const o of lines(text)) {
    const role = o.role ?? o.type;
    if (role === "tool" || role === "tool_call") { toolUses += 1; recognized = true; continue; }
    if (role !== "assistant") continue;
    recognized = true;
    const c = o.content ?? o.message?.content ?? o.text;
    const t = textOf(c); if (t) parts.push(t);
    toolUses += toolBlocks(c);
    const calls = o.tool_calls ?? o.toolCalls;
    if (Array.isArray(calls)) toolUses += calls.length;
  }
  return { assistantText: parts.join("\n"), toolUses, recognized };
}

export function assistantTextOrNull(parsed) {
  return parsed && parsed.recognized ? parsed.assistantText : null;
}
