/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EdgesFromOpts {
  to?: string
  type?: string
  openOnly?: boolean
}
export interface TraverseOpts {
  edgeTypes?: Array<string>
  direction?: string
  asOf?: number
}
export interface SearchTextOpts {
  recencyWeight?: number
  recencyHalfLifeMs?: number
  nowMs?: number
}
export interface RecallVector {
  model: string
  vector: Array<number>
}
export interface RecallOpts {
  vector?: RecallVector
  expansions?: any
  graphBoost?: boolean
  labels?: Array<string>
  nowMs?: number
}
export interface SuggestLinksOpts {
  model?: string
  asOf?: number
  minSemanticSimilarity?: number
}
export declare class Subscription {
  /**
   * Async next with optional timeout (milliseconds). None on timeout or disconnect.
   * Disconnect ends iteration cleanly by returning Ok(None).
   */
  next(timeoutMs?: number | undefined | null): Promise<any | null>
  /** Close the subscription by dropping the receiver. */
  close(): void
}
export type TopoDb = TopoDB
export declare class TopoDB {
  static open(path: string): Promise<TopoDb>
  static openWith(path: string, indexSpec: any): Promise<TopoDb>
  formatVersion(): Promise<number>
  close(): void
  submit(commands: any, defaultScope?: string | undefined | null, nowMs?: number | undefined | null): Promise<any>
  node(scopes: Array<string>, id: string): Promise<any | null>
  nodesByLabel(scopes: Array<string>, label: string): Promise<any>
  nodesByLabelNewest(scopes: Array<string>, label: string, k: number): Promise<any>
  nodesByProp(scopes: Array<string>, label: string, prop: string, value: any): Promise<any>
  nodesByPropNormalized(scopes: Array<string>, label: string, prop: string, value: any): Promise<any>
  nodesByFloatRange(scopes: Array<string>, prop: string, min: number, max: number): Promise<any>
  edgesFrom(scopes: Array<string>, from: string, opts?: EdgesFromOpts | undefined | null): Promise<any>
  allEdgesBetween(from: string, to: string): Promise<any>
  openEdgesBetween(from: string, to: string): Promise<Array<string>>
  traverse(scopes: Array<string>, seeds: Array<string>, maxHops: number, opts?: TraverseOpts | undefined | null): Promise<any>
  searchText(scopes: Array<string>, query: string, k: number, opts?: SearchTextOpts | undefined | null): Promise<any>
  searchVector(scopes: Array<string>, model: string, vector: Array<number>, k: number, candidates?: Array<string> | undefined | null): Promise<any>
  recall(scopes: Array<string>, query: string, k: number, opts?: RecallOpts | undefined | null): Promise<any>
  suggestLinks(scopes: Array<string>, node: string, k: number, opts?: SuggestLinksOpts | undefined | null): Promise<any>
  /** Subscribe to change feed with given buffer capacity. */
  subscribe(capacity: number): Subscription
  /** Get all operations since a given sequence number. */
  opsSince(seq: number): Promise<Array<any>>
  /** Get the current sequence number. */
  currentSeq(): Promise<number>
  /** Compact operations, keeping from the given sequence. */
  compactOps(keepFrom: number): Promise<void>
  /** Get the index specification. */
  indexSpec(): Promise<any>
  /** Get storage report with table statistics. */
  storageReport(): Promise<Array<any>>
  /**
   * Get access statistics for a node. Returns null if node doesn't exist.
   * Returns {accessCount, lastAccessedAt} where accessCount is 0 for never-accessed existing nodes.
   */
  accessStats(scopes: Array<string>, id: string): Promise<any | null>
  /** Rebuild state from operations (replay ops log). */
  rebuildStateFromOps(): Promise<void>
  /** Open an existing database from storage. */
  static openStored(path: string): Promise<TopoDb>
  /** Open database with options (index spec and optional cache size). */
  static openWithOptions(path: string, indexSpec: any, cacheSizeBytes?: number | undefined | null): Promise<TopoDb>
  /** Unstable debug surface — shape may change without notice. */
  debugDumpNodes(): Promise<Array<any>>
  /** Unstable debug surface — shape may change without notice. */
  debugDumpEdges(): Promise<Array<any>>
}
