// GENERATED by scripts/sync-plugin-core.mjs from plugins/core — edit there, then re-run the sync.
// warehouse-spool.js — pure helpers for landing raw context into the
// warehouse spool (spec §6.1). Redaction/size policy is the Rust drain's job.
import { appendFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { createHash, randomBytes } from "node:crypto";
import path from "node:path";
import { encodeUlid } from "./scope-id.js";

export const SPOOL_HARD_CAP = 4 * 1024 * 1024;
export const HARNESS = "claude-code";
const off = (v) => { const s = String(v ?? "").trim().toLowerCase(); return s === "0" || s === "off"; };
export function warehouseDisabled(env) { return off(env.TOPODB_RECORDING) || off(env.TOPODB_WAREHOUSE); }
/** Where the plugin's db lives (server-args.js launches the server on it). */
export const DB_FILE = "memory.redb";
/** `TOPODB_WAREHOUSE_DIR` → nearest `.topodb.toml` `[warehouse] path` (walking
 *  up from the data dir, where memory.redb lives) → `<dataDir>/memory.warehouse`.
 *  Same rule as the daemon (`resolve_warehouse`), so one setting steers both. */
export function warehouseDir(dataDir, env) {
  return resolveWarehouse(path.join(dataDir, DB_FILE), env ?? {}).dir;
}
/** Off when an env switch says so OR the nearest `.topodb.toml` has
 *  `[warehouse] enabled = false` (which env cannot re-enable, as in Rust). */
export function warehouseOff(dataDir, env) {
  return warehouseDisabled(env ?? {}) || !resolveWarehouse(path.join(dataDir, DB_FILE), env ?? {}).enabled;
}
// ---- .topodb.toml [warehouse] (spec 2026-08-24-plugins-toml-parity) --------
/** Filesystem seam for the toml lookup; tests inject a map. */
export const nodeIo = {
  existsFile: (p) => { try { return statSync(p).isFile(); } catch { return false; } },
  readFile: (p) => readFileSync(p, "utf8"),
};
/** Mirrors topodb-mcp's `nearest_topodb_toml`: from the db's parent directory
 *  upward, the first regular file named `.topodb.toml`. Never resolves a
 *  relative db — Rust walks `Path::parent()` on the literal path. */
export function nearestTopodbToml(db, io = nodeIo) {
  let dir = path.dirname(db);
  for (;;) {
    const cand = path.join(dir, ".topodb.toml");
    if (io.existsFile(cand)) return cand;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}
/** The two `[warehouse]` keys the hooks need, from a tolerant line-level parse
 *  (comments, blank lines, `[table]`/`[[array]]` headers, `key = value` with a
 *  bare boolean or a quoted string). Rust rejects a malformed file entirely;
 *  this may still read a well-formed `[warehouse]` table out of one. */
export function parseWarehouseToml(text) {
  const out = { enabled: true };
  let section = "";
  for (const raw of String(text ?? "").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const hdr = /^\[\[?\s*([^\]]+?)\s*\]\]?$/.exec(line);
    if (hdr) { section = hdr[1]; continue; }
    if (section !== "warehouse") continue;
    const kv = /^([A-Za-z0-9_-]+)\s*=\s*(.+)$/.exec(line);
    if (!kv) continue;
    const key = kv[1];
    const rawVal = kv[2].trim();
    if (key === "enabled") {
      const val = rawVal.replace(/\s+#.*$/, "").trim();
      if (val === "true" || val === "false") out.enabled = val === "true";
    } else if (key === "path") {
      // A quoted string keeps everything inside its quotes (a `#` there is
      // not a comment); only what follows the closing quote may be one.
      const q = /^"([^"]*)"|^'([^']*)'/.exec(rawVal);
      const p = q ? (q[1] ?? q[2]) : undefined;
      if (p) out.path = p;
    }
  }
  return out;
}
/** Mirrors `topodb_onboarding::resolve_warehouse`: toml `enabled = false`
 *  disables regardless of env; then `TOPODB_WAREHOUSE=0|off`; dir = non-blank
 *  `TOPODB_WAREHOUSE_DIR` → toml `path` (`~/` → HOME / USERPROFILE on win32,
 *  expanding even when set-but-empty like Rust's `var_os`; relative → the
 *  toml's directory) → `<db>.warehouse`. An unreadable toml counts as absent. */
export function resolveWarehouse(db, env, io = nodeIo) {
  const tomlPath = nearestTopodbToml(db, io);
  let section = { enabled: true };
  if (tomlPath) { try { section = parseWarehouseToml(io.readFile(tomlPath)); } catch { /* unreadable → defaults, as Rust */ } }
  const envDir = env?.TOPODB_WAREHOUSE_DIR;
  let dir, source;
  if (envDir && String(envDir).trim()) { dir = String(envDir); source = "env"; }
  else if (tomlPath && section.path) {
    const home = env?.[process.platform === "win32" ? "USERPROFILE" : "HOME"];
    const p = section.path.startsWith("~/") && home !== undefined ? path.join(home, section.path.slice(2)) : section.path;
    dir = path.isAbsolute(p) ? p : path.join(path.dirname(tomlPath), p);
    source = "toml";
  } else {
    const ext = path.extname(db);
    dir = (ext ? db.slice(0, -ext.length) : db) + ".warehouse";
    source = "default";
  }
  return { enabled: section.enabled && !off(env?.TOPODB_WAREHOUSE), dir, source };
}
export function newUlid(nowMs = Date.now()) {
  const b = new Uint8Array(16);
  let t = BigInt(Math.max(0, Math.floor(nowMs)));
  for (let i = 5; i >= 0; i--) { b[i] = Number(t & 0xffn); t >>= 8n; }
  b.set(randomBytes(10), 6);
  return encodeUlid(b);
}
export function spoolPath(dataDir, sessionId, env) {
  const safe = String(sessionId).replace(/[^A-Za-z0-9._-]/g, "_");
  return path.join(warehouseDir(dataDir, env), "spool", `${safe}-${process.pid}.jsonl`);
}
export function appendSpool(dataDir, sessionId, event, env) {
  const p = spoolPath(dataDir, sessionId, env);
  mkdirSync(path.dirname(p), { recursive: true });
  appendFileSync(p, JSON.stringify(event) + "\n");
}
// ---- spool growth cap (spec 2026-08-24-pi-warehouse-followups §4/§5b) ------
export const DEFAULT_SPOOL_MAX_MB = 64;
/** `TOPODB_WAREHOUSE_SPOOL_MAX_MB` in bytes: `0` = unlimited; unset, blank,
 * non-numeric or negative → 64 MB. Same rule as the pi extension. */
export function spoolCapBytes(env) {
  const dflt = DEFAULT_SPOOL_MAX_MB * 1024 * 1024;
  const raw = env?.TOPODB_WAREHOUSE_SPOOL_MAX_MB;
  if (raw === undefined || String(raw).trim() === "") return dflt;
  const n = Number(raw);
  return Number.isFinite(n) && n >= 0 ? Math.floor(n * 1024 * 1024) : dflt;
}
/** Total bytes of every file under `<warehouse>/spool` (any extension —
 * `.draining` leftovers are backlog too); 0 when the directory is absent.
 * Returns early once `limit` is reached, so callers that only need an
 * over/under answer pay O(cap), not O(backlog). */
export function spoolBytes(dataDir, env, limit = Infinity) {
  const spool = path.join(warehouseDir(dataDir, env), "spool");
  let total = 0;
  try {
    for (const f of readdirSync(spool)) {
      try { total += statSync(path.join(spool, f)).size; } catch { /* drained mid-walk */ }
      if (total >= limit) return total;
    }
  } catch { return 0; }
  return total;
}
const CAPPED_SENTINEL = "spool-capped";
/** True when the spool backlog is at/over cap and the artifact must be
 * dropped. Every hook is its own short-lived process, so "log once per
 * over-cap episode" is a sentinel file `<warehouse>/spool-capped`: created
 * (with one console.error) on the first drop, removed by the next call that
 * sees the total under cap again. Markers never consult this. */
export function spoolOverCap(dataDir, env) {
  const cap = spoolCapBytes(env);
  if (cap <= 0) return false;
  const sentinel = path.join(warehouseDir(dataDir, env), CAPPED_SENTINEL);
  if (spoolBytes(dataDir, env, cap) < cap) {
    try { if (existsSync(sentinel)) unlinkSync(sentinel); } catch { /* best-effort */ }
    return false;
  }
  if (!existsSync(sentinel)) {
    try { mkdirSync(path.dirname(sentinel), { recursive: true }); writeFileSync(sentinel, ""); } catch { /* best-effort */ }
    console.error(`topodb warehouse: spool cap (${cap / (1024 * 1024)} MB) reached; artifacts dropped until the server drains it`);
  }
  return true;
}
export function simpleDiff(oldStr, newStr) {
  const o = String(oldStr ?? "").split("\n"), n = String(newStr ?? "").split("\n");
  if (o.length && o[o.length - 1] === "") o.pop();
  if (n.length && n[n.length - 1] === "") n.pop();
  let head = 0; while (head < o.length && head < n.length && o[head] === n[head]) head++;
  let tail = 0; while (tail < o.length - head && tail < n.length - head && o[o.length - 1 - tail] === n[n.length - 1 - tail]) tail++;
  const lines = ["--- old", "+++ new"];
  for (const l of o.slice(head, o.length - tail)) lines.push("-" + l);
  for (const l of n.slice(head, n.length - tail)) lines.push("+" + l);
  return lines.join("\n") + "\n";
}
function firstText(x) {
  if (typeof x === "string") return x;
  if (Array.isArray(x)) { const t = x.find((b) => b && typeof b === "object" && b.type === "text" && typeof b.text === "string"); return t ? t.text : undefined; }
  return undefined;
}
export function responseText(toolName, toolInput, resp) {
  if (resp === null || resp === undefined) return undefined;
  if (typeof resp === "string") return resp;
  if (Array.isArray(resp)) return firstText(resp);
  if (typeof resp !== "object") return String(resp);
  if (resp.file && typeof resp.file.content === "string") return resp.file.content;
  if (typeof resp.stdout === "string") return resp.stdout + (resp.stderr ? "\n[stderr]\n" + resp.stderr : "");
  for (const k of ["content", "result", "output", "text"]) {
    const v = resp[k];
    if (typeof v === "string") return v;
    const t = firstText(v); if (t !== undefined) return t;
  }
  try { return JSON.stringify(resp); } catch { return undefined; }
}
const TYPES = { Read: "file_read", Bash: "command", Edit: "diff", MultiEdit: "diff", Write: "diff", Grep: "tool_output", Glob: "tool_output", WebFetch: "tool_output" };
function locatorFor(toolName, ti) {
  switch (toolName) {
    case "Read": case "Edit": case "MultiEdit": case "Write": return ti.file_path;
    case "Bash": return ti.command;
    case "Grep": case "Glob": return ti.pattern;
    case "WebFetch": return ti.url;
    default: return undefined;
  }
}
export function artifactEvent({ toolName, toolInput, toolResponse, sessionId, scope, cwd, agent, harness = HARNESS, nowMs = Date.now() }) {
  const type = TYPES[toolName];
  if (!type) return null;
  const ti = toolInput && typeof toolInput === "object" ? toolInput : {};
  let text;
  if (toolName === "Edit") text = simpleDiff(ti.old_string, ti.new_string);
  else if (toolName === "MultiEdit") text = (Array.isArray(ti.edits) ? ti.edits : []).map((e) => simpleDiff(e?.old_string, e?.new_string)).join("\n");
  else if (toolName === "Write") text = typeof ti.content === "string" ? ti.content : undefined;
  else text = responseText(toolName, ti, toolResponse);
  if (typeof text !== "string") return null;
  const locator = String(locatorFor(toolName, ti) ?? "");
  const artifact = { type, locator, bytes: Buffer.byteLength(text, "utf8") };
  if (artifact.bytes > SPOOL_HARD_CAP) artifact.hash = "sha256:" + createHash("sha256").update(text, "utf8").digest("hex");
  else artifact.content = text;
  const source = { harness, session: String(sessionId), scope: String(scope), tool: toolName };
  if (cwd) source.cwd = String(cwd);
  if (agent) source.agent = String(agent);
  return { id: newUlid(nowMs), ts: nowMs, host: "", kind: "artifact", v: 1, source, artifact };
}
export function markerEvent({ type, sessionId, scope, nodeIds = [], harness = HARNESS, nowMs = Date.now() }) {
  const marker = { type, harness, session: String(sessionId), scope: String(scope) };
  if (nodeIds.length) marker.node_ids = nodeIds.map(String);
  return { id: newUlid(nowMs), ts: nowMs, host: "", kind: "marker", v: 1, marker };
}

export function tryMarker({ dataDir, env, projectDir, sessionId, type, nodeIds = [], sessionScopes, harness = HARNESS, scope: scopeOverride }) {
  try {
    if (!dataDir || !sessionId || !projectDir || warehouseOff(dataDir, env)) return;
    // A write with an explicit scope lands there; the marker must say so or
    // derive looks the memory up in the wrong scope set.
    const scope = scopeOverride ?? sessionScopes({ projectDir }).scope;
    appendSpool(dataDir, sessionId, markerEvent({ type, sessionId, scope, nodeIds, harness }), env);
  } catch { /* best-effort */ }
}
